#!/usr/bin/env bash
set -e
#set -x

# Clear the last preview (if any)
~/.config/lf/image clear

# Calculate where the image should be placed on the screen.
num=$(printf "%0.f\n" "`echo "$(tput cols) / 3 + 8" | bc`")
numb=$(printf "%0.f\n" "`echo "$(tput cols) - $num - 10" | bc`")
numc=$(printf "%0.f\n" "`echo "$(tput lines) - 19" | bc`")

case "$1" in
    *.persist)
        /opt/syslog-ng/bin/persist-tool dump "$1"|awk -F '["=]' '/(qfile\(|\.queue|java)/ { gsub(/[ \t]+/, "", $5); gsub(/^[0-9A-Fa-f]{8}/, "", $5); "echo "$5"|xxd -r -p"|& getline QUEUE; printf("%s ==> %s\n",$1,QUEUE)} /http/{gsub(/^[0-9A-Fa-f]{8}/, "", $5);"echo "$5"|xxd -r -p"|& getline QUEUE; printf("%s ==> %s\n",$1,QUEUE)} '
        ;;
    *.qf|*.rqf|*.qf.corrupted|*.rqf.corrupted)
        /opt/syslog-ng/bin/dqtool info "$1" 2>&1|awk 'gsub(/, /, "\n", $0) gsub(/; /, "\n",$0)'
        ;;
    *messages.store|*.lgs)
        /opt/syslog-ng/bin/lgstool inspect "$1" 2>&1|awk 'gsub(/, /, ",\n", $0)' ;;
    *.crt|*.cer|*.pem) openssl x509 -noout -text -in "$1"|tail +3;;
    *.rrd)
        OUTFILE=$(mktemp /tmp/rrdtemp.XXXXXXXX)
        rrdtool graph "$OUTFILE" -w 800 -h 600 --start $(rrdinfo "$1"|awk '/step /{STEP=$3} /last_update /{LAST_UPDATE=$3} /rows /{ROWNUM=$3}END{LAST_UPDATE-=ROWNUM*STEP;print LAST_UPDATE }') --end $(rrdinfo "$1"|awk '/last_update/{print $3}') DEF:load=$1:42:AVERAGE LINE1:load#FF0000:"$(basename $1)" >/dev/null
        $HOME/.config/lf/image draw "$OUTFILE" $num 4 $numb $numc
        ;;
	*.tgz|*.tar.gz) tar tzf "$1";;
	*.tar.bz2|*.tbz2) tar tjf "$1";;
	*.tar.txz|*.txz) xz --list "$1";;
    *.xz) xz --list "$1" ;;
    *.gz) gunzip -l "$1";;
	*.tar) tar tf "$1";;
	*.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1";;
	*.rar) unrar l "$1";;
	*.7z) 7z l "$1";;
	*.[1-8]) man "$1" | col -b ;;
	*.o) nm "$1" | less ;;
	#*.torrent) transmission-show "$1";;
	*.iso) iso-info --no-header -l "$1";;
	*odt,*.ods,*.odp,*.sxw) odt2txt "$1";;
    *.rtf) unrtf --quiet --text "$1";;
	*.doc) catdoc "$1" ;;
	*.docx) docx2txt "$1" - ;;
    *.json) jq -C <"$1" ;;
#	*.csv) cat "$1" | sed s/,/\\n/g ;;
	*.pdf)
		CACHE=$(mktemp /tmp/thumbcache.XXXXX)
		pdftoppm -png -f 1 -singlefile "$1" "$CACHE"
		$HOME/.config/lf/image draw "$CACHE.png" $num 4 $numb $numc
		;;
	*.epub)
		CACHE=$(mktemp /tmp/thumbcache.XXXXX)
		epub-thumbnailer "$1" "$CACHE" 1024
		$HOME/.config/lf/image draw "$CACHE" $num 4 $numb $numc
		;;
	*.bmp|*.jpg|*.jpeg|*.png|*.xpm|*.PNG|*.BMP|*.JPEG|*.PNG|*.XPM)
		~/.config/lf/image draw "$1" $num 4 $numb $numc
        #w3m "$1"
		;;
	*.wav|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus|*.as[fx]|*.flac) exiftool "$1";;
	*.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx)
		CACHE=$(mktemp /tmp/thumbcache.XXXXX)
		ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
		$HOME/.config/lf/image draw "$CACHE" $num 4 $numb $numc
		;;
	*)
        case $(file --mime-type "$1" -bL) in
            application/json) jq -C <"$1" ;;
            *) highlight -O ansi "$1" || cat "$1" ;;
        esac
        ;;
esac
